Repository RCOS-EasyContact/EasyContact, pull requests merged in 2021-10, with the labels that each got.

#16 Backend - Database Reconstruction
  Backend/ContactSystem/Book.h
  Backend/ContactSystem/Contact.cpp
  Backend/ContactSystem/Contact.h
  Backend/ContactSystem/ContactBook.cpp
  Backend/ContactSystem/ContactBook.h
  Backend/ContactSystem/GroupContact.cpp
  Backend/ContactSystem/GroupContact.h
  Backend/ContactSystem/Key.h
  Backend/ContactSystem/Tags.cpp
  Backend/ContactSystem/Tags.h
  Backend/ContactSystem/Triple.h
  Backend/MainExecutable.cpp
  Backend/Makefile
  Backend/SignalHandler.h
Labels: Breaking Change

#21 Workflow - C++ Linter Filter [C++11 Standard]
  .github/workflows/Lint(CPP).yml
Labels: Improvement

#20 Backend - MainExecutable Reconstruction
  Backend/Executable/GlobalMutex.hpp
  Backend/Executable/Main.cpp
  Backend/Executable/README.md
  Backend/MainExecutable.cpp
  Backend/Makefile
  Backend/README.md
Labels: Breaking Change, Documentation

#23 Frontend - Login Page & Main Page
  Frontend/README.md
  Frontend/html-version/bg1.jpg
  Frontend/html-version/sign.css
  Frontend/html-version/sign_in.html
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/favicon.ico
  Frontend/public/index.html
  Frontend/public/logo192.png
  Frontend/public/logo512.png
  Frontend/public/manifest.json
  Frontend/public/robots.txt
  Frontend/src/App.css
  Frontend/src/App.js
  Frontend/src/chat/chat-form/Chat-Form.css
  Frontend/src/chat/chat-form/Chat-Form.js
  Frontend/src/chat/chat-title/Chat-Title.css
  Frontend/src/chat/chat-title/Chat-Title.js
  Frontend/src/chat/conversation/Conversation-Item.css
  Frontend/src/chat/conversation/Conversation-Item.js
  Frontend/src/chat/conversation/Conversation-List.css
  Frontend/src/chat/conversation/Conversation-List.js
  Frontend/src/chat/conversation/New-Conversation.css
  Frontend/src/chat/conversation/New-Conversation.js
  Frontend/src/chat/message/Message-List.css
  Frontend/src/chat/message/Message-List.js
  Frontend/src/chat/search/Chat-Search.css
  Frontend/src/chat/search/Chat-Search.js
  Frontend/src/chat/shell/Chat-Shell.css
  Frontend/src/chat/shell/Chat-Shell.js
  Frontend/src/components/Backdrop.js
  Frontend/src/components/Modal.js
  Frontend/src/components/Todo.js
  Frontend/src/images/icons/attachment-logo.svg
  Frontend/src/images/icons/trash-logo.svg
  Frontend/src/images/profiles/ben.png
  Frontend/src/images/profiles/daryl.png
  Frontend/src/images/profiles/douglas.png
  Frontend/src/images/profiles/jacob.png
  Frontend/src/images/profiles/john.jpeg
  Frontend/src/images/profiles/kim.jpeg
  Frontend/src/images/profiles/sarah.jpeg
  Frontend/src/images/profiles/stacey.jpeg
  Frontend/src/images/profiles/stan.jpeg
  Frontend/src/images/search/search.svg
  Frontend/src/index.css
  Frontend/src/index.js
Labels: New Feature

#25 Frontend - Login Page
  .FILES/LOGO/LOGO_200x200.png
  .FILES/LOGO/LOGO_500x500.png
  .FILES/LOGO/LOGO_NEW_2388x1668.png
  .FILES/LOGO/LOGO_NEW_SVG.svg
  .github/workflows/Lint(CSS).yml
  Frontend/sign.css
  Frontend/sign_in.html
  README.md
Labels: Improvement, New Feature

#26 Workflow - CSS Linter Config
  .FILES/CONFIG/.stylelintrc.json
  .github/workflows/Lint(CPP).yml
  .github/workflows/Lint(CSS).yml
  README.md
Labels: Improvement

#35 Document - MailClient & SQLContacts
  Backend/Executable/README.md
  Backend/MailClient/README.md
  Backend/SQLContacts/README.md
Labels: Documentation
