Repository RCOS-EasyContact/EasyContact, pull requests merged in 2021-11, with the labels that each got.

#36 SQLContacts- Reconstruction Rev.2 Part.2
  .github/workflows/CodeQL(CPP).yml
  .gitignore
  Backend/API/APIRouter.hpp
  Backend/API/README.md
  Backend/Executable/MultiClientMain.cpp
  Backend/MailClient/MailClient.cpp
  Backend/MailClient/MailClient.hpp
  Backend/MailClient/example_test_file/MailClient.cpp
  Backend/MailClient/example_test_file/MailClient.hpp
  Backend/MailClient/example_test_file/temp_readme.md
  Backend/SQLContacts/Contacts.cpp
  Backend/SQLContacts/Contacts.hpp
Labels: New Feature

#37 API - Authenticate RCSID Sign In
  .github/workflows/CodeQL(CPP).yml
  .gitignore
  .gitmodules
  Backend/API/APIRouter.hpp
  Backend/API/README.md
  Backend/API/UserToken.hpp
  Backend/Executable/MultiClientMain.cpp
  Backend/Executable/SingleUser.hpp
  Backend/Executable/SysLogs.hpp
  Backend/MailClient/MailClient.cpp
  Backend/MailClient/MailClient.hpp
  Backend/SQLContacts/Contacts.cpp
  Backend/SQLContacts/Contacts.hpp
  CMakeLists.txt
  UserData/README.md
Labels: New Feature

#38 Document - Redirect Install Guide
  .FILES/WIKI/INSTALL-GUIDE.md
  README.md
Labels: Documentation

#39 API - Integrate SQLContact
  Backend/API/APIRouter.hpp
  Backend/API/README.md
  Backend/API/UserToken.hpp
  Backend/Executable/MultiClientMain.cpp
  Backend/Executable/SysLogs.hpp
  Backend/MailClient/MailClient.cpp
  Backend/MailClient/MailClient.hpp
  Backend/SQLContacts/Contacts.cpp
  Backend/SQLContacts/Contacts.hpp
Labels: New Feature

#40 Document - API Specifications
  Backend/API/README.md
Labels: Documentation

#41 Frontend - Integrate Login
  Backend/API/APIRouter.hpp
  Frontend/server.js
  Frontend/sign_in.html
  Frontend/test.html
Labels: Bug-Fix, Improvement

#42 API - Dispatch Queue Implementation
  .github/workflows/CodeQL(CPP).yml
  .gitmodules
  Backend/API/APIRouter.hpp
  Backend/API/UserToken.hpp
  Backend/Executable/DispatchQueue.cpp
  Backend/Executable/DispatchQueue.hpp
  Backend/Executable/MultiClientMain.cpp
  Backend/Executable/SingleUser.cpp
  Backend/Executable/SingleUser.hpp
  Backend/Executable/SysLogs.hpp
  Backend/MailClient/MailClient.cpp
  Backend/MailClient/MailClient.hpp
  Backend/SQLContacts/Contacts.cpp
  Backend/SQLContacts/Contacts.hpp
  CMakeLists.txt
Labels: New Feature

#44 API - Integrate MailClient
  .gitignore
  Backend/README.md
  Backend/bin/README.md
  Backend/doc/README.md
  Backend/include/EasyContact/Contacts.hpp
  Backend/include/EasyContact/DispatchQueue.hpp
  Backend/include/EasyContact/HTTPRouter.hpp
  Backend/include/EasyContact/MailClient.hpp
  Backend/include/EasyContact/SingleUser.hpp
  Backend/include/EasyContact/SysLogs.hpp
  Backend/include/EasyContact/UserToken.hpp
  Backend/include/README.md
  Backend/lib/README.md
  Backend/src/Contacts.cpp
  Backend/src/DispatchQueue.cpp
  Backend/src/MailClient.cpp
  Backend/src/SingleUser.cpp
Labels: New Feature

#45 Frontend - Chat Dashboard Layout
  Frontend/README.md
  Frontend/data/messages.js
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.css
  Frontend/src/App.js
  Frontend/src/chat/chat-form/Chat-Form.css
  Frontend/src/chat/chat-form/Chat-Form.js
  Frontend/src/chat/chat-title/Chat-Title.js
  Frontend/src/chat/conversation/Conversation-List.css
  Frontend/src/chat/conversation/Conversation-List.js
  Frontend/src/chat/message/Message-List.css
  Frontend/src/chat/message/Message-List.js
  Frontend/src/chat/search/Chat-Search.css
  Frontend/src/chat/search/Chat-Search.js
  Frontend/src/chat/shell/Chat-Shell.css
  Frontend/src/chat/shell/Chat-Shell.js
  Frontend/src/components/Backdrop.js
  Frontend/src/components/Modal.js
  Frontend/src/components/Todo.js
  Frontend/src/components/chat-form/Chat-Form.css
  Frontend/src/components/chat-form/Chat-Form.js
  Frontend/src/components/chat-title/Chat-Title.css
  Frontend/src/components/chat-title/Chat-Title.js
  Frontend/src/components/conversation/conversation-item/Conversation-Item.css
  Frontend/src/components/conversation/conversation-item/Conversation-Item.js
  Frontend/src/components/conversation/conversation-list/Conversation-List.css
  Frontend/src/components/conversation/conversation-list/Conversation-List.js
  Frontend/src/components/conversation/conversation-search/Conversation-Search.css
  Frontend/src/components/conversation/conversation-search/Conversation-Search.js
  Frontend/src/components/conversation/new-conversation/New-Conversation.css
  Frontend/src/components/conversation/new-conversation/New-Conversation.js
  Frontend/src/components/message/Message-List.css
  Frontend/src/components/message/Message-List.js
  Frontend/src/components/message/Message.css
  Frontend/src/components/message/Message.js
  Frontend/src/containers/shell/Chat-Shell.css
  Frontend/src/containers/shell/Chat-Shell.js
  Frontend/src/index.js
  Frontend/src/store/actions/index.js
  Frontend/src/store/reducers/conversations.js
  Frontend/src/store/reducers/index.js
Labels: Bug-Fix, Improvement, New Feature
