Repository RCOS-EasyContact/EasyContact, pull requests merged in 2021-09, with the labels that each got.

#1 Backend - Class <Contact> Implementation
  Backend/Contact.h
Labels: Documentation, New Feature

#2 Backend - Class <GroupContact> Implementation
  Backend/Contact.h
  Backend/GroupContact.h
Labels: New Feature

#4 Backend - Class <GroupContact> Bug-Fix
  Backend/GroupContact.h
Labels: Bug-Fix

#5 Workflow - C++ Linter Setup
  .github/workflows/CodeQL(JavaScript).yml
  .github/workflows/Lint(CPP).yml
  Backend/Contact.h
  Backend/GroupContact.h
  README.md
Labels: New Feature

#6 Proposal - New Logo Design
  .FILES/LOGO_NEW_2388x1668.png
  README.md
Labels: Improvement

#7 Proposal - New Logo Format Conversion
  .FILES/LOGO_NEW_SVG.svg
  README.md
Labels: Documentation

#9 Proposal - License Update
  LICENSE.md
  README.md
Labels: Improvement

#8 Backend - Class <ContactBook> Implementation
  Backend/Contact.h
  Backend/ContactBook.h
  Backend/GroupContact.h
Labels: Bug-Fix, Documentation, New Feature

#11 Workflow - C++ CodeQL Fix
  .github/workflows/CodeQL(CPP).yml
Labels: Bug-Fix

#12 Document - Add CodeQL Badge
  README.md
Labels: Documentation

#14 Workflow - Allow Skipping Commit CI
  .github/workflows/CodeQL(CPP).yml
  .github/workflows/CodeQL(JavaScript).yml
  .github/workflows/Lint(CPP).yml
Labels: Improvement

#13 Backend - Header <SignalHandler> Implementation
  Backend/ContactBook.h
  Backend/ContactSystem/Contact.cpp
  Backend/ContactSystem/Contact.h
  Backend/ContactSystem/ContactBook.cpp
  Backend/ContactSystem/ContactBook.h
  Backend/ContactSystem/GroupContact.cpp
  Backend/ContactSystem/GroupContact.h
  Backend/GroupContact.h
  Backend/MainExecutable.cpp
  Backend/Makefile
  Backend/SignalHandler.h
Labels: Breaking Change
